apiVersion: {{ include "rasa-common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "rasa-common.names.fullname" . }}
  labels:
    {{- include "rasa-common.labels.standard" . | nindent 4 }}
    {{- if .Values.deploymentLabels }}
{{ toYaml .Values.deploymentLabels | indent 4 }}
    {{- end }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.hostAliases }}
  hostAliases:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
  selector:
    matchLabels:
      {{- include "rasa-common.labels.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/config-map.yaml") . | sha256sum }}
{{- if and .Values.nginx.enabled .Values.nginx.tls.enabled .Values.nginx.tls.generateSelfSignedCert  }}
        checksum/nginx-tls-secret: {{ include (print $.Template.BasePath "/nginx-tls-secret.yaml") . | sha256sum }}
{{- end }}
{{- if and .Values.nginx.enabled }}
        checksum/nginx-config: {{ include (print $.Template.BasePath "/nginx-config-map.yaml") . | sha256sum }}
{{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rasa-common.labels.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: "{{ include "rasa-common.names.serviceAccount" . }}"
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if or .Values.initContainers (eq (include "rasa.initialModel.download" .) "true") (eq (include "rasa.initialModel.train" .) "true") }}
      initContainers:
        {{- if .Values.initContainers }}
        {{- toYaml .Values.initContainers | nindent 8 }}
        {{- end }}
        {{- if eq (include "rasa.initialModel.download" .) "true" }}
        {{- include "rasa.downloadInitialModel.initContainer" . | nindent 8 }}
        {{- else if eq (include "rasa.initialModel.train" .) "true" }}
        {{- include "rasa.trainInitialModel.initContainer" . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
      {{- if .Values.extraContainers }}
        {{- toYaml .Values.extraContainers | nindent 8 }}
      {{- end }}
{{- (include "rasa.nginx.sidecar" .)  | nindent 8 }}
        - name: rasa-oss
          {{- if .Values.args }}
          args:
{{ toYaml .Values.args | indent 12 }}
          {{- else }}
          args:
            {{- include "rasa.rasa.server.type" . | nindent 12 }}
            - --port
            - "{{ .Values.applicationSettings.port }}"
            - --cors
            - {{- if .Values.applicationSettings.cors }} {{ .Values.applicationSettings.cors | quote }}{{ end }}
            - --jwt-method
            - HS256
            - --jwt-secret
            - "$(JWT_SECRET)"
            - --auth-token
            - "$(RASA_TOKEN)"
        {{- if .Values.extraArgs }}
        {{- toYaml .Values.extraArgs | nindent 12 }}
        {{- end }}
            {{ if .Values.applicationSettings.debugMode }}- --debug{{ end }}
          {{- end }}
          {{- if .Values.command }}
          command:
{{ toYaml .Values.command | indent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "rasa-common.images.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.applicationSettings.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- include "rasa.containers.env" . | nindent 12 }}
          volumeMounts:
          {{- if or (eq (include "rasa.initialModel.download" .) "true") (eq (include "rasa.initialModel.train" .) "true") }}
          {{- include "rasa.initialModel.initContainer.volumeMounts" . | nindent 12 }}
          {{- end }}
          {{- include "rasa.containers.volumeMounts" . | nindent 12 }}
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 12 }}
{{- end }}
      volumes:
      {{- if or (eq (include "rasa.initialModel.download" .) "true") (eq (include "rasa.initialModel.train" .) "true") }}
      {{- include "rasa.initialModel.initContainer.volumes" . | nindent 8 }}
      {{- end }}
      {{- include "rasa.containers.volumes" . | nindent 8 }}
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 8 }}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
